=== bharatxnj/edureka_java_jee/src/com/edureka/module6/company.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT company (name, address, employees) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT address (city,state,zip) | (state, city,zip) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT state (#PCDATA) >
<!ELEMENT zip (#PCDATA) >
<!ELEMENT employees (employee+) >
<!ELEMENT employee (id, name, age, dob, projects*) >
<!ELEMENT dob (date, month,year) | (month,date,year
<!ELEMENT id (#PCDATA) >
<!ELEMENT age (#PCDATA) >
<!ELEMENT projects (project+) >
<!ELEMENT project (id,client) >
<!ELEMENT client (name,location) >

=== bharatxnj/edureka_java_jee/src/com/edureka/module6/company1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "company.dtd" >
<company>
  <name>name</name>
  <address>
    <city>city</city>
    <state>state</state>
    <zip>zip</zip>
  </address>
  <employees>
    <employee>
      <id>id</id>
      <name>name</name>
      <age>age</age>
    </employee>
  </employees>
</company>
