=== bharatxnj/edureka_java_jee/src/com/edureka/module6/company.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="company">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"></xs:element>
				<xs:element name="address">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="state" type="xs:string"></xs:element>
							<xs:element name="city" type="xs:string"></xs:element>
							<xs:element name="zip" type="xs:positiveInteger"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="employees">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="employee" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="id" type="xs:positiveInteger"
											minOccurs="1" maxOccurs="1"></xs:element>
										<xs:element name="name" type="xs:string" minOccurs="1"
											maxOccurs="1"></xs:element>
										<xs:element name="age" type="xs:positiveInteger"
											minOccurs="1" maxOccurs="1"></xs:element>
										<xs:element name="dob">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="date" type="xs:positiveInteger"></xs:element>
													<xs:element name="month" type="xs:positiveInteger"></xs:element>
													<xs:element name="year" type="xs:positiveInteger"></xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bharatxnj/edureka_java_jee/src/com/edureka/module6/company_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="company.xsd">
  <name>name</name>
  <address>
    <state>state</state>
    <city>city</city>
    <zip>1</zip>
  </address>
  <employees>
    <emplyee>
      <id>1</id>
      <name>name</name>
      <age>1</age>
      <dob>
        <date>1</date>
        <month>1</month>
        <year>1</year>
      </dob>
    </emplyee>
  </employees>
</company>
