=== bharatxnj/edureka_java_jee/src/com/edureka/module6/shiporder.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="shiporder">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="orderperson" type="xs:string"/>
      <xs:element name="shipto">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" nillable="false"/>
            <xs:element name="address" minOccurs="1" maxOccurs="unbounded">
            	<xs:complexType>
            		<xs:sequence>
	            		<xs:element name="city" type="xs:string"/>
	            		<xs:element name="state" type="xs:string"/>
	            		<xs:element name="country" type="xs:string"/>
            		</xs:sequence>
            	</xs:complexType>
            </xs:element>
           </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="item" maxOccurs="unbounded" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="note" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="quantity" type="xs:positiveInteger"/>
            <xs:element name="price" type="xs:decimal"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="orderid" type="xs:string" use="optional"/>
  </xs:complexType>
</xs:element>
</xs:schema>

=== bharatxnj/edureka_java_jee/src/com/edureka/module6/shiporder.xml
<?xml version="1.0" encoding="UTF-8"?>
<shiporder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="shiporder.xsd">
	<orderperson>myOrder</orderperson>
	<shipto>
		<name>Pradeep</name>
		<address>
			<city>Bangalore</city>
			<state>Karnataka</state>
			<country>India</country>
		</address>
		<address>
			<city>Bangalore</city>
			<state>Karnataka</state>
			<country>India</country>
		</address>
		<address>
			<city>Bangalore</city>
			<state>Karnataka</state>
			<country>India</country>
		</address>
	</shipto>
	<item>
		<title>book</title>
		<note>dsfdsfdsf</note>
		<note>dsfdsfdsf</note>
		<note>dsfdsfdsf</note>
		<note>dsfdsfdsf</note>
		<note>dsfdsfdsf</note>
		<quantity>1</quantity>
		<price>10.0</price>
	</item>
	<item>
		<title>book</title>
		<quantity>1</quantity>
		<price>10.0</price>

	</item>
	<item>
		<title>book</title>
		<quantity>1</quantity>
		<price>10.0</price>
	</item>
</shiporder>

=== bharatxnj/edureka_java_jee/src/com/edureka/module6/shiporder1sdfsdf.xml
<?xml version="1.0" encoding="UTF-8"?>
<shiporder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shiporder.xsd">
  <orderperson>orderperson</orderperson>
  <shipto>
    <name>name</name>
    <address>
      <city>city</city>
      <state>state</state>
      <country>country</country>
    </address>
  </shipto>
  <item>
    <title>title</title>
    <quantity>1</quantity>
    <price>0.0</price>
  </item>
</shiporder>

=== bharatxnj/edureka_java_jee/src/com/edureka/module6/shiporder-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<shiporder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shiporder.xsd">
  <orderperson>orderperson</orderperson>
  <shipto>
    <name>fsdfsdf</name>
    <address>1st E Main</address>
    <city>Bangalore</city>
    <country>India</country>
  </shipto>
  <item>
    <title>Laptop</title>
    <quantity>1</quantity>
    <price>2900000.00</price>
  </item>
</shiporder>
