=== bharatxnj/edureka_java_jee/src/com/edureka/module6/Test.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT employee (name,age?, address+,from,dob,profession)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT address (house-no, street?, lane, city, state, zip)>
<!ELEMENT house-no (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT lane (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT dob ((date,month,year)|(month,date,year) )>
<!ELEMENT date (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT profession (#PCDATA)>

=== bharatxnj/edureka_java_jee/bin/com/edureka/module6/test_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employee PUBLIC "employee" "Test.dtd" >
<employee>
	<name>Pradeep</name>
	<age>21</age>
	<address>
		<house-no>22</house-no>
		<lane>8</lane>
		<city>Bangalore</city>
		<state>Karnataka</state>
		<zip>544554</zip>
	</address>
	<address>
		<house-no>22</house-no>
		<street>7th Main</street>
		<lane>8</lane>
		<city>Bangalore</city>
		<state>Karnataka</state>
		<zip>544554</zip>
	</address>
	<from>Hydrabad</from>
	<dob>
		<month>05</month>
		<date>21</date>
		<year>1983</year>
	</dob>
	<profession>Developer</profession>
</employee>
